#!/bin/sh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/st4
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/st4/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/st4
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

# pick two 12z valid times
ymdh1=2022092912
ymdh2=2022093012
ymd1=`echo $ymdh | cut -c3-8`
ymd2=`echo $ymdh | cut -c3-8`

DAPATH=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian
fmdl1=${DAPATH}/st4_${ymdh1}.grd
cp ${DAPATH}/st4_${ymdh2}.grd fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1 + fmdl2
 GDATTIM  = 30/12 
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = add(p24i^${ymd2}/12+2,p24i^${ymd1}/12) 
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   STAGE IV 48-HR TOTAL PCP
 DEVICE   = GIF|st4pcp48_${ymdh2}.gif|750;900
 SATFIL   =
 RADFIL   =`
# PROJ     = lcc/25;-84;25;/1;1;1;1
 PROJ     = lcc/25;-86;25;/1;1;1;1
 GAREA    = 23;-92.;35.;-78 
# GAREA    = 27.;-86.2;37.;-74.
# GAREA    = 31.;-86.;41.;-72.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.85/0.7;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.25;1.5;1.75;2;2.5;3;4;5;7;10;15;20;30
 FLINE    = 0;21;22;23;4;25;26;27;28;29;30;14;15;2;17;18;19;20;11;31
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

   gdplot2 << EOF
 DEVICE   =  GIF|st4pcp48thresh_${ymdh2}.gif|750;900 
 FINT     = 10;15;20;30
 FLINE    = 0;5;10;2;11
r

ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
