#!/bin/sh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/gfspcp
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/gfspcp/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/gfspcp
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

ymdh=2022092612
ymd=`echo $ymdh | cut -c1-8`
ym=`echo $ymdh | cut -c3-8`
cyc=`echo $ymdh | cut -c9-10`

DAPATH=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian
fmdl1=${DAPATH}/gfspcp_${ymdh}
hours="96"

for fhr in $hours
do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p48i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 48-HR TOTAL PCP
 DEVICE   = GIF|gfspcp48_${ymdh}f${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
# PROJ     = lcc/25;-84;25;/1;1;1;1
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = 24.;-92.;34.;-78 
# GAREA    = 27.;-86.2;37.;-74.
# GAREA    = 31.;-86.;41.;-72.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.85/0.7;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.25;1.5;1.75;2;2.5;3;4;5;7;10;15;20;30
 FLINE    = 0;21;22;23;4;25;26;27;28;29;30;14;15;2;17;18;19;20;11;31
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
