#!/bin/ksh

set -x

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/hireswpcp
rm /lfs/h2/emc/stmp/geoffrey.manikin/hireswpcp/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/hireswpcp/

ymdh=2022092812
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
version=v8.1

#DAPATH=/com2/hiresw/prod/hiresw.${ymd}
DAPATH=/lfs/h1/ops/prod/com/hiresw/${version}/hiresw.${ymd}
#DAPATH=/lfs/h2/emc/ptmp/geoffrey.manikin/hiresw
OUT=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian/
WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib

fhrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for fhr in $fhrs
do

typeset -Z2 fhra fhr3
fhr3=`expr $fhr - 3`
if [ $fhr3 -lt 10 -a $fhr3 -gt 0 ]; then
typeset -Z1 fhr3
fi

fhra=$fhr
if [ $fhr -lt 10 ]; then
typeset -Z1 fhra
fi

if [ $fhr -eq 03 ]; then
fhr3=0
typeset -Z1 fhr3
fi

if [ $fhr -eq 3 ];then
 echo "APCP:surface:0-3 hour acc fcst" >> pcp.fil
else
 echo "APCP:surface:${fhr3}-${fhra} hour acc fcst" >> pcp.fil
fi

wgrib2 ${DAPATH}/hiresw.t${cyc}z.fv3_5km.f${fhr}.conus.grib2 | grep -F -f pcp.fil | wgrib2 -i -grib new.fil ${DAPATH}/hiresw.t${cyc}z.fv3_5km.f${fhr}.conus.grib2

   nagrib2 << EOF
GBFILE  = new.fil 
INDXFL  =
GDOUTF  = dummyhires1.grd 
PROJ    =
GRDAREA =
KXKY    = 
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF
rm new.fil pcp.fil
done
mv dummyhires1.grd $OUT/hireswfv3pcp_${ymdh}

for fhr in $fhrs
do

typeset -Z2 fhra fhr3
fhr3=`expr $fhr - 3`
if [ $fhr3 -lt 10 -a $fhr3 -gt 0 ]; then
typeset -Z1 fhr3
fi

fhra=$fhr
if [ $fhr -lt 10 ]; then
typeset -Z1 fhra
fi

if [ $fhr -eq 03 ]; then
fhr3=0
typeset -Z1 fhr3
fi

if [ $fhr -eq 3 ];then
 echo "APCP:surface:0-3 hour acc fcst" >> pcp.fil
else
 echo "APCP:surface:${fhr3}-${fhra} hour acc fcst" >> pcp.fil
fi

wgrib2 ${DAPATH}/hiresw.t${cyc}z.arw_5km.f${fhr}.conus.grib2 | grep -F -f pcp.fil | wgrib2 -i -grib new.fil ${DAPATH}/hiresw.t${cyc}z.arw_5km.f${fhr}.conus.grib2

   nagrib2 << EOF
GBFILE  = new.fil
INDXFL  =
GDOUTF  = dummyhires2.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

rm new.fil pcp.fil
done
mv dummyhires2.grd $OUT/hireswarwpcp_${ymdh}

for fhr in $fhrs
do

typeset -Z2 fhra fhr3
fhr3=`expr $fhr - 3`
if [ $fhr3 -lt 10 -a $fhr3 -gt 0 ]; then
typeset -Z1 fhr3
fi

fhra=$fhr
if [ $fhr -lt 10 ]; then
typeset -Z1 fhra
fi

if [ $fhr -eq 03 ]; then
fhr3=0
typeset -Z1 fhr3
fi

if [ $fhr -eq 3 ];then
 echo "APCP:surface:0-3 hour acc fcst" >> pcp.fil
else
 echo "APCP:surface:${fhr3}-${fhra} hour acc fcst" >> pcp.fil
fi

wgrib2 ${DAPATH}/hiresw.t${cyc}z.arw_5km.f${fhr}.conusmem2.grib2 | grep -F -f pcp.fil | wgrib2 -i -grib new.fil ${DAPATH}/hiresw.t${cyc}z.arw_5km.f${fhr}.conusmem2.grib2

   nagrib2 << EOF
GBFILE  = new.fil
INDXFL  =
GDOUTF  = dummyhires3.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

rm new.fil pcp.fil
done
mv dummyhires3.grd $OUT/hireswarw2pcp_${ymdh}
exit


for fhr in $fhrs
do

wgrib ${DAPATH}/conusfv3.t${cyc}z.awp5kmf${fhr} | grep kpds5=211:kpds6=105  | wgrib ${DAPATH}/conusfv3.t${cyc}z.awpreg${fhr} -i -grib -o new2.fil
wgrib ${DAPATH}/conusfv3.t${cyc}z.awp5kmf${fhr} | grep kpds5=212:kpds6=200  | wgrib ${DAPATH}/conusfv3.t${cyc}z.awpreg${fhr} -i -grib -o new3.fil
wgrib ${DAPATH}/conusarw.t${cyc}z.awp5kmf${fhr} | grep kpds5=211:kpds6=105  | wgrib ${DAPATH}/conusarw.t${cyc}z.awpreg${fhr} -i -grib -o new4.fil
wgrib ${DAPATH}/conusarw.t${cyc}z.awp5kmf${fhr} | grep kpds5=212:kpds6=200  | wgrib ${DAPATH}/conusarw.t${cyc}z.awpreg${fhr} -i -grib -o new5.fil

   nagrib << EOF
GBFILE  = new2.fil
INDXFL  =
GDOUTF  = dummyhires3.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = new3.fil
r

exit
EOF

   nagrib << EOF
GBFILE  = new4.fil
INDXFL  =
GDOUTF  = dummyhires4.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = new5.fil
r

exit
EOF

rm new*.fil
done

mv dummyhires3.grd hireswfv3_${ymdh}
mv dummyhires4.grd hireswarw_${ymdh}
exit
